### ISSUE TITLE
Add pre-commit hooks

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#12]
_Originally posted by @real-yfprojects in [a comment to issue #1](https://github.com/akaihola/darglint2/issues/1#issuecomment-1437534712_):
            
>Will you add pre-commit hooks?

<details><summary>This is what I would use</summary>

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # frozen: v4.4.0
    hooks:
      # check file system problems
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      # unify whitespace and line ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending

      # sort requirements.txt files
      - id: requirements-txt-fixer

      # python code
      - id: fix-encoding-pragma

      # check more
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/python-poetry/poetry
    rev: "fb493f2e80a11403fa289617a703ae622d4ccd75" # frozen: 1.3.0
    hooks:
      - id: poetry-check

  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 6fd6194c7bbd629b18a7bcd7a4a38a57f128b451 # 0.4.0
    hooks:
      - id: sync_with_poetry
        files: ".pre-commit-config.yaml|poetry.lock"

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "cafd5506f18eea191804850dacc0a4264772d59d" # frozen: v3.0.0-alpha.4
    hooks:
      - id: prettier

  # only when we are using rST based docs
  - repo: https://github.com/rstcheck/rstcheck
    rev: "77751d7a7d81a5d47aa344d802f41809c4d063c0" # frozen: v6.1.1
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx]
        args: ["--config", "docs/rstcheck.cfg"]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: cc27459d0f843a9333dd181e7451a8d041591a25 # frozen: v0.12.1
    hooks:
      - id: validate-pyproject
        files: pyproject.toml$

  # your favourite linters, I personally use pylama
  - repo: local
    hooks:
      - id: pylama
        name: pylama
        entry: pylama
        language: system
        types: [python]

# configuration for the pre-commit.ci bot
# only relevant when actually using the bot
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  autofix_prs: true # default
  autoupdate_branch: "develop"
  autoupdate_commit_msg: |
    [pre-commit.ci] Autoupdate pre-commit hook versions.

    for more information, see https://pre-commit.ci, https://pre-commit.com and
    the `.pre-commit-config.yaml` file in this repository.

  submodules: false # default

```

</details>
