### ISSUE TITLE
Update `bnf_to_cnf` `poetry.lock`

### ISSUE THREAD

**Issue by akaihola** [akaihola/darglint2#8]
E.g. update from 
```toml
name = "darglint"
version = "1.1.0"
```
to
```toml
name = "darglint2"
version = "1.8.2"
```
